### ISSUE TITLE
这个和 swiftTheme 主要差别在哪里?

### ISSUE THREAD

**Issue by VineFiner** [Tkoul/TKThemeConfig#1]

**Comment by Tkoul** [comment]
你好，为了你这个问题，我特意去看了swiftTheme 的源码。下面是我的浅薄见解：
为贴合开发者习惯，对外api大都相同，所以在使用上看不出什么。包括百度，腾讯的设计。
但是俩sdk主要的设计核心思想完全不同。
1.怎么全局变更主题，swiftTheme用到的是注册，移除通知。个人觉得重了，观察者模式很耗性能。如果创建1W,2W,5W,10W个各种类别View组件，可以体验下两者效率。TKThemeConfig轻量级的block局部变量，用hash表管理，工作原理简单，性能高，跟随类dealloc后，探测类存在与否，进行自我销毁，与项目耦合度极低。
2.swiftTheme对UIKit重新定义了api，定义了规范。所有的基于ThemePicker自成的空间。TKThemeConfig 更贴合原属性进行定制了部分组件，研究起来很简单，这块两者实现目的都差不多，但是在系统api，有些组件，类，并不继承UIView，它依然有color，image，tincolor等属性。而TKThemeConfig设计了万能用法tkThemeChangeBlock。比如UITableViewRowAction这个类，ThemePicker无能为力，因为swiftTheme未拓展。
3.拓展性：UIKit 家族是不断壮大的，你不可能去对每个组件进行拓展，不能一劳永逸，TKThemeConfig做到了。因为万能用法涵盖一切新的，除非他不继承与object，然而这不可能。

ps：研究了下swiftTheme，发现作者很厉害，有许多需要学习借鉴的地方。很多点，很点睛！时间有限，我只是粗略看了下。说错的地方望谅解😀

**Comment by VineFiner** [comment]
你说的这个 hash 表 是字典吗？

我最近也在研究暗黑模式。

经过对比 感觉百度的相对好一些。但是没有开源。

腾讯的 QMUI 使用也相对方便，但是不能单独集成。会比较臃肿。

关于对外 api， 微软的理念是接近原生。以后升级，更加容易替换。

> 参考 [百度暗黑模式](https://mp.weixin.qq.com/s?__biz=MzUxMzk2ODI1NQ==&mid=2247483925&idx=1&sn=90a668648fa9c57e8b6a2adac0556bb7&chksm=f94c5305ce3bda13745d6fce34661dd3a5720958bae5376a34de8087b3d6da508649c752ac0c&scene=27#wechat_redirect)

> [腾讯](https://qmuiteam.com/)

> [京东](https://mp.weixin.qq.com/s/w4fWrpX4vSOF79aHBo_G4Q)

> [优酷](https://developer.aliyun.com/article/741622)

>  [微软](https://github.com/microsoft/FluentDarkModeKit)

**Comment by VineFiner** [comment]
现在我在着手实现百度暗黑的形式。我自己对 Runtime 不是很熟悉。所以如果你觉得好的话，可以一起实现。如果不认同，就关闭这个 issue 吧。

**Comment by Tkoul** [comment]
hash表通俗的说就是字典，不过hash表本身就是一个数组。感兴趣可以研究下hash表的设计实现。
百度的这个文章我看了，它的量级很大。因为要统一几百个团队的组件资源（百度app就一个空壳，它是通过集成百度上百个团队的sdk组件）。在暗黑的基础上考录到多团队资源重合问题，混合开发问题，UI资源一致性问题。剥离开这些，暗黑核心就是怎么跟随系统或者定义的主题让app去实现变更主题，与其它的关系不大。百度在使用- (void)didMoveToSuperview这个方法执行时机去储存View树，在变更主题的时候，遍历储存器变更主体，个人认为不是好的设计方案。首先didMoveToSuperview局限性强，只有继承UIView才会有。layer就不具备，很多类也不具备。做不到万能使用。并且如果他的sdk开源，应该不比腾讯的量级轻。
       还有，百度的暗黑组件目前有BUG。不知道什么时候解决。现在手机百度app（ios端），打开设置- >显示与亮度，打开手机百度app，双击home键，进入到多任务界面，来回切换主题，多任务快照的界面不会跟随主题变更。只有点击进入到前台才会变更。你可以下载一个体验下

这是我的demo效果（ps不要在意丑的细节😀）：https://v.youku.com/v_show/id_XNDcwNTcxODMwNA==.html

你可以动手去设计实现一番，有很多细节。runtime的问题我可以帮你回答，你把你qq发我邮件Tkoull@163.com ，我加你。我对runtime了解很深  😀    你可以看看我的另外一个组件，万能路由组件：TKRouter  就是runtime的完美实现。

本来设计的也有多资源重合去除实现。但是作为上班族的我时间精力都有限。

**Comment by VineFiner** [comment]
好的，谢谢。
